### PR TITLE
Adjusted code for non-square images

### PR DESCRIPTION
**Pull request by nextcam**
Adjusted code for non-square images. Added a note regarding key length for Logistic Encryption/Decryption

### CODE REVIEW

**Comment by sukhaniya** [comment]
> Adjusted code for non-square images. Added a note regarding key length for Logistic Encryption/Decryption



> Adjusted code for non-square images. Added a note regarding key length for Logistic Encryption/Decryption

hey @nextcam i am recently working on a project and this project giving me some idea but ,I want this to be medical images instead of horizon d lena.jpg ,I tried to replace but I am getting so many error ,if you have executed the whole project do plz help me get over this error  contact me (hannahharry121997@gmail.com) it will be grt help

**Comment by nextcam** [comment]
Which kind of error are you talking about?

**Comment by sukhaniya** [comment]
For that I need your email id

**Comment by sukhaniya** [comment]
Hey
 Plz help me with this!!
 It will grt

Thank you

**Comment by sukhaniya** [comment]
> Which kind of error are you talking about?

hey @nextcam i ant to replace this image with medical image but idk I am getting so many error why is this happening plz help

**Comment by sukhaniya** [comment]
> Adjusted code for non-square images. Added a note regarding key length for Logistic Encryption/Decryption

hay what all API she used in this project??? any idea

**Pull request merged**
